version: 2
updates:
  # Hold actions brukt i de gjenbrukbare workflowene og actionene oppdatert
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    commit-message:
      prefix: "⬆️ "
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
