name: Bygg image

on:
  workflow_call:
    inputs:
      modul:
        description: 'Modulen som skal bli til et image'
        required: true
        type: string
    outputs:
      image_ref:
        description: 'Referanse til det bygde imaget'
        value: ${{ jobs.bygg-image.outputs.image_ref }}

jobs:
  bygg-image:
    name: Bygg image
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      actions: read # for sarif upload on private repos
      contents: read
      id-token: write # for nais login
      security-events: write # push sarif to github security
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
      with:
        distribution: temurin
        java-version: 25

    - uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

    - name: NAIS login
      id: login
      uses: nais/login@40b72a35a18ddf2ad74b632461139ab838cc2a2f # v0
      with:
        team: tbd

    - name: gradlew :${{ inputs.modul }}:jib
      id: jib
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./gradlew :${{ inputs.modul }}:jib --build-cache \
          -Pimage.registry='${{ steps.login.outputs.registry }}' \
          -Pimage.tag=$(date -u +%Y.%m.%d-%H.%M)-$(git rev-parse --short=12 HEAD) \
          -Djib.console=plain
        ref="$(cat '${{ inputs.modul }}/build/jib-image.name')@$(cat '${{ inputs.modul }}/build/jib-image.digest')"
        echo "ref=$ref" >> "$GITHUB_OUTPUT"

    - name: Generer SBOM, attester og signer
      uses: nais/attest-sign@61e94c81cec0784078969aefa8e136bf343cfd7d # v2.0.16
      with:
        image_ref: ${{ steps.jib.outputs.ref }}

    - name: Scan docker image for secrets
      uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
      with:
        image-ref: ${{ steps.jib.outputs.ref }}
        format: 'sarif'
        scanners: 'secret'
        output: 'trivy.sarif'

    - uses: github/codeql-action/upload-sarif@1c5b675653bb5c22dbe9b12b556ec555138e09fd # v4.38.1
      with:
        sarif_file: 'trivy.sarif'
    outputs:
      image_ref: ${{ steps.jib.outputs.ref }}
