name: Bygg og test modul

on:
  workflow_call:
    inputs:
      modul:
        description: 'Modulen som skal bygges og testes'
        required: true
        type: string

jobs:
  bygg-og-test:
    name: Bygg og test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: temurin
          java-version: 25

      - uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

      - name: gradlew clean :${{ inputs.modul }}:build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODUL: ${{ inputs.modul }}
        run: ./gradlew clean ":$MODUL:build" --build-cache
