name: Deploy

on:
  workflow_call:
    inputs:
      CLUSTER:
        description: 'Which Nais cluster to deploy into.'
        required: true
        type: string
      RESOURCE:
        description: 'Comma-separated list of files containing Kubernetes resources. Must be JSON or YAML format.'
        required: true
        type: string
      VARS:
        description: 'File containing template variables. Will be interpolated with the $RESOURCE file. Must be JSON or YAML format.'
        required: false
        default: '/dev/null'
        type: string
      WORKLOAD_IMAGE:
        description: 'Use this image in a companion Image resource.'
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write # for nais login
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: NAIS login
      uses: nais/login@40b72a35a18ddf2ad74b632461139ab838cc2a2f # v0
      with:
        team: tbd

    - name: Deploy
      uses: nais/deploy/actions/deploy@1de80da70ad26556ecdc5964a8b7ec3bbed98120 # v2
      env:
        CLUSTER: ${{ inputs.CLUSTER }}
        RESOURCE: ${{ inputs.RESOURCE }}
        VARS: ${{ inputs.VARS }}
        WORKLOAD_IMAGE: ${{ inputs.WORKLOAD_IMAGE }}
